name: ${project.name}
main: com.github.rlf.bitcloud.BitCloud
version: ${project.version}
description: bitCloud for Bukkit v${project.version}
author: R4zorax
depend: []
softdepend: []
commands:
    bitcloud:
        description: Primary bitCloud command
        aliases: [bc]
        usage:  |
             /<command> help - shows additional help
permissions:
  bitcloud.*:
    default: op
    description: Giver spilleren adgang til /mc god kommandoen